name: Android Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build for Android
        run: |
          export NDK_HOME=$ANDROID_NDK_ROOT
          cargo install cargo-ndk
          cargo ndk -t arm64-v8a -t armeabi-v7a -t x86_64 build --release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/aarch64-linux-android/release/program
            target/armv7-linux-androideabi/release/program
            target/x86_64-linux-android/release/program
          generate_release_notes: true
