name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target=aarch64-linux-android --target=armv7-linux-androideabi --target=x86_64-linux-android
    - name: Run tests
      run: cargo test --verbose
